name: Convert recipes flow

on:
  push:
  workflow_dispatch:

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Run build with Gradle Wrapper
      working-directory: ./convert-tool 
      run: | 
         ./gradlew standaloneJar
         tree
    - name: Run converter
      run: | 
         java -jar convert-tool/app/build/libs/recipes-converter-all.jar \
         --action convert --sourceAll recipes \
          --destination Recipes \
          --agpVersion 8.0.0-alpha10 --gradleVersion 7.5.1 --overwrite
          tree
    - name: Cleaning folders and commit
      run: |
       cd Recipes
       git init
       git checkout --orphan agp8.0.0-alpha10
       git config user.name "GitHub Actions"
       git config user.email noreply@github.com
       git add .
       git commit --message "Prepare release"
       git push --set-upstream origin agp8.0.0-alpha10
